POST https://gpsbackend2022.herokuapp.com/login
Content-type: application/json

{
    "email":"kuldeep@gmail.com",
    "password":"kuldeep123"
}
###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1567",
"DeviceType":"Aircraft",
"Timestamp":"31-08-2022 10:05",
"location":"L1"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1567",
"DeviceType":"Aircraft",
"Timestamp":"31-08-2022 10:10",
"location":"L1"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1567",
"DeviceType":"Aircraft",
"Timestamp":"31-08-2022 10:15",
"location":"L1"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1567",
"DeviceType":"Aircraft",
"Timestamp":"31-08-2022 10:20",
"location":"L1"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1567",
"DeviceType":"Aircraft",
"Timestamp":"31-08-2022 10:25",
"location":"L2"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1568",
"DeviceType":"Personal",
"Timestamp":"31-08-2022 10:05",
"location":"L3"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1568",
"DeviceType":"Personal",
"Timestamp":"31-08-2022 10:10",
"location":"L3"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1568",
"DeviceType":"Personal",
"Timestamp":"31-08-2022 10:15",
"location":"L3"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1568",
"DeviceType":"Personal",
"Timestamp":"31-08-2022 10:20",
"location":"L3"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1568",
"DeviceType":"Personal",
"Timestamp":"31-08-2022 10:25",
"location":"L3"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1569",
"DeviceType":"Asset",
"Timestamp":"31-08-2022 10:15",
"location":"L4"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1569",
"DeviceType":"Asset",
"Timestamp":"31-08-2022 10:20",
"location":"L4"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1569",
"DeviceType":"Asset",
"Timestamp":"31-08-2022 10:25",
"location":"L1"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1569",
"DeviceType":"Asset",
"Timestamp":"31-08-2022 10:30",
"location":"L1"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1569",
"DeviceType":"Asset",
"Timestamp":"31-08-2022 10:35",
"location":"L2"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1570",
"DeviceType":"Personal",
"Timestamp":"31-08-2022 10:35",
"location":"L5"
}

###
POST https://gpsbackend2022.herokuapp.com/addGpsData
Content-type: application/json

{
"DeviceId":"D-1571",
"DeviceType":"Asset",
"Timestamp":"31-08-2022 10:35",
"location":"L6"
}